### ISSUE TITLE
Root for you.!👍

### ISSUE THREAD

**Issue by Abracadabraba** [DearDawalish/WinXray#1]
DearDawalish

It turns out I am using a fake version of Winxray after reading your README, so despicable. I was confused when I found it has commercials but thought it might a way for the coder to get some income. Thanks for telling us the truth, and I am using your version now. Glad you keep updating, and wish better releases come soon. 
Currently, Vless Reality should be a better protocol, fully supported already?
Root for you.!👍

Abra

**Comment by DearDawalish** [comment]
谢谢你的支持。
WinXray底层是在调用各个Core。使用Vless协议时，调用的是xray core，而xray core完美支持Vless，所以理论上来讲，WinXray也是完美支持Vless的。

**Comment by Abracadabraba** [comment]
感谢解答，已了解知悉，试验了一个真的可以链接。很棒。
看到今天又发布了4.6.3，能否在程序上加上关于---》版本---》检测更新等功能，这样可以随时更新主程序。
谢谢您！👍

**Comment by DearDawalish** [comment]
WinXray一直都是有检测更新的功能的。
原版检测是直接下载更新包，下次启动时自动更新。但是这样做需要一台服务器来存放更新包。TheMRLL的做法是将更新包放到源码里，由于git备份历史文件的机制，会导致源码异常庞大，所以我不考虑这种更新方式。而在国内找一个地方来存放更新包的话，始终会存在有被回溯的可能，从而被请去喝茶。
所以我退而求其次，将原来这个更新按钮，修改为跳转到本项目的release界面。
![image](https://github.com/DearDawalish/WinXray/assets/135088527/8868dbac-ee5d-4ae2-a02e-b744d45b5a05)

**Comment by Abracadabraba** [comment]
晓得了，感谢告知。静待后续您的作品。👍
