### ISSUE TITLE
用pre-release的1.8.3 core出错了

### ISSUE THREAD

**Issue by Abracadabraba** [DearDawalish/WinXray#10]
大佬，
我把1.8.3 pre-release core文件放到xray core下替换当前版本xray core文件后，程序提示

Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 windows/amd64)
A unified platform for anti-censorship.
Failed to start: main: failed to load config files: [config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:win-spy > infra/conf: failed to load geosite: WIN-SPY > infra/conf: list not found in geosite.dat: WIN-SPY

这个问题咋处理啊?
叩谢！

**Comment by DearDawalish** [comment]
pre-release就是不稳定版，切回稳定版的core。更新core用程序里的按钮，别自己搞。

![image](https://github.com/DearDawalish/WinXray/assets/135088527/b98742be-443d-4979-bffb-02fe072efe62)

**Comment by Abracadabraba** [comment]
好的！谢谢大佬。
