### ISSUE TITLE
xray core更新到1.8.4后，console窗口版本还显示1.7.5

### ISSUE THREAD

**Issue by pl-660** [DearDawalish/WinXray#12]
winxray程序版本：v4.6.6
![Snipaste_2023-09-05_17-20-10](https://github.com/DearDawalish/WinXray/assets/73865792/04ea04e4-08d7-425a-9660-6427e66be072)
![Snipaste_2023-09-05_17-19-59](https://github.com/DearDawalish/WinXray/assets/73865792/833a2eb6-08c5-4fb1-ab4d-4129c0c0d102)

**Comment by DearDawalish** [comment]
已修复
