### ISSUE TITLE
naiveproxy core更新后，再次点击依然会更新，不显示无需更新

### ISSUE THREAD

**Issue by pl-660** [DearDawalish/WinXray#13]
4.6.7版本，core配置页面中，点击“下载/更新naiveproxy core”，更新至最新版后，再次点击还会进入更新流程，没有提示"已是最新版本，无需更新"

**Comment by DearDawalish** [comment]
这么久了，我还没遇到过这个协议的节点。这个小缺陷也没什么影响，不打算修了(･･;)

**Comment by DearDawalish** [comment]
4.6.8版本已修复
