### ISSUE TITLE
编辑PAC窗口分辨率和UWP允许后仍旧无法走代理的问题

### ISSUE THREAD

**Issue by Abracadabraba** [DearDawalish/WinXray#2]
DearDawalish,
反馈两个问题，
1. 编辑PAC窗口，在1366*768及以下老旧电脑的分辨率下，显示不全，必须手动调整窗口才能看到底部的按钮；
2. UWP应用配置，设置全部允许之后，依旧不能走代理。这个在win10和win11上测试过都不行。典型代表就是那个whatsapp，毕竟那个软件PC上只有UWP版。
这个问题并不是您的版本才有，那个版本上也有，因为您还在更新，不晓得是否可以验证一下，如果真有问题可否解决一下？
谢谢您！

**Comment by DearDawalish** [comment]
pac窗口已经改了，[代码](https://github.com/DearDawalish/WinXray/commit/8301c5c1635c48e95a8d59ef780621ba751eb333)，不过这个小功能我不想发release了，你自己打包吧

**Comment by Abracadabraba** [comment]
好的。收到。UWP的问题您再费心验证一下啊。👍

**Comment by DearDawalish** [comment]
我测试了下，WinXray代理UWP应用是没有问题的。
我首先拿Skype来测试，可以正常登录。
然后我拿WhatsApp来测试，发现是应用连接的地址很多本身就不通，即使用海外的服务器测试，也是不通的，并不是本地代理的问题。
比如这里，168.143.171.93的443端口，即使海外服务器也不通。
本地端口：
![端口](https://github.com/DearDawalish/WinXray/assets/135088527/a6f9ef77-d693-48f3-b12c-5bfc07e8cbc3)
海外服务器测试：
![image](https://github.com/DearDawalish/WinXray/assets/135088527/aa35789c-8299-4f99-a80a-d3eb79604fc8)
WhatsApp每次启动都会随机选择应用里地址池，其中有些地址是通的，我多次启动后，当选择到`15.197.206.217:5222`这个地址时，二维码便刷出来了。
所以综上，issue中提到的WhatsApp无法走代理，其实是WhatsApp应用中的地址本身就不通的问题。

**Comment by Abracadabraba** [comment]
了解，谢谢。原来是Whatsapp自己的锅。那没办法了，谢谢！
