### ISSUE TITLE
Vless 连接问题

### ISSUE THREAD

**Issue by Abracadabraba** [DearDawalish/WinXray#3]
DearDawalish,
我使用同一个Vless连接，粘贴导入WinXray，显示这样
![image](https://github.com/DearDawalish/WinXray/assets/108131195/727d1269-6277-4e38-baa9-84cb59cbb10b)
但是同一个链接，粘贴导入新版V2RayN, 却是可以使用的
![image](https://github.com/DearDawalish/WinXray/assets/108131195/aa55e2cd-80ed-4cc9-a3cc-4e075bb1f195)
节点编辑页面，WinXray的编辑选项要少很多，好几个都没有，
![image](https://github.com/DearDawalish/WinXray/assets/108131195/01eaa100-4fb1-4bac-aa6f-e899621ff785)
![image](https://github.com/DearDawalish/WinXray/assets/108131195/a03bc6f8-d22d-482a-8ee7-7f530eb0ff3c)

请问这个问题怎么处理解决呢？

**Comment by DearDawalish** [comment]
我需要一些信息来排查：

- V2rayN

1. 将你的v2rayN vless协议的core设置为xray
2. 将你提到的这个节点设置为活动的服务器
3. 提供 `v2rayN根目录/guiConfigs/config.json` 中，`outbounds` 字段的内容，服务器地址和端口你可以脱敏，其余保留，粘贴到这个issue里

- WinXray

1. 将上面提到的节点设置为活动的服务器
2. 提供 `WinXray根目录/core/xray/config.json` 中，`outbounds` 字段的内容，服务器地址和端口你可以脱敏，其余保留，粘贴到这个issue里

**Comment by Abracadabraba** [comment]
查看了一下，V2rayN我的默认Xray核，已经更新到最新版。
"outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "我的地址",
            "port": 443,
            "users": [
              {
                "id": "我的ID",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": ""
              }
            ]
          }
        ]
      },


WinXray的不是如上显示的，我就凭我自己理解复制了以下字段，如果有问题还请再告知。

"outbounds":[{"protocol":"vless","tag":"proxy","mux":{"concurrency":8,"enabled":true},"settings":{"vnext":[{"address":"我的地址","port":443,"users":[{"encryption":"none","id":"我的ID","level":0}]}]},

**Comment by DearDawalish** [comment]
我怀疑你改过配置，把flow改掉了，因为代码里是有设置这个的，但是你发的配置没有，你可以手动添加，这样应该就可以了
![image](https://github.com/DearDawalish/WinXray/assets/135088527/1233d8ca-b424-4589-ba4d-7c20941a0844)

**Comment by Abracadabraba** [comment]
收到，我尝试添加到config里面。为了验证是不是我手动搞过（我自己也记不清楚），我今早上把所有节点全删了，然后又重新导入节点，再打开config文件，里面的内容如下，

{"inbounds":[{"listen":"127.0.0.1","port":1081,"protocol":"socks","tag":"proxy","settings":{"auth":"noauth","udp":true},"sniffing":{"destOverride":["http","tls"],"enabled":true}},{"listen":"127.0.0.1","port":1082,"protocol":"http","tag":"http_proxy","settings":{},"sniffing":{"destOverride":["http","tls"],"enabled":true}}],"outbounds":[{"protocol":"vless","tag":"proxy","mux":{"concurrency":8,"enabled":true},"settings":{"vnext":[{"address":"我的地址","port":443,"users":[{"encryption":"none","id":"我的ID","level":0}]}]},"streamSettings":{"network":"ws","security":"tls","tlsSettings":{"allowInsecure":false,"serverName":"我的地址"},"wsSettings":{"path":"/?ed=2048","headers":{"Host":"我的地址"}}}},{"protocol":"dns","tag":"Dns-Out"},{"protocol":"freedom","tag":"Direct","settings":{"domainStrategy":"UseIPv4"}},{"protocol":"blackhole","tag":"Reject","settings":{"response":{"type":"http"}}}],"dns":{"servers":["https://dns.google/dns-query",{"address":"https+local://223.5.5.5/dns-query","domains":["geosite:cn","geosite:icloud"],"expectIPs":["geoip:cn"]},{"address":"https://1.1.1.1/dns-query","domains":["geosite:geolocation-!cn"]}],"hosts":{"dns.google":"8.8.8.8","doh.pub":"119.29.29.29"}},"log":{"access":"","error":"","loglevel":"warning"},"routing":{"domainStrategy":"IPIfNonMatch","rules":[{"outboundTag":"Direct","protocol":["bittorrent"],"type":"field"},{"inboundTag":["Socks-In","Http-In"],"network":"udp","outboundTag":"Dns-Out","port":53,"type":"field"},{"domain":["geosite:category-ads-all","geosite:win-spy"],"outboundTag":"Reject","type":"field"},{"domain":["full:www.icloud.com","domain:icloud-content.com"],"outboundTag":"proxy","type":"field"},{"domain":["geosite:tld-cn","geosite:icloud"],"outboundTag":"Direct","type":"field"},{"domain":["geosite:geolocation-!cn"],"outboundTag":"proxy","type":"field"},{"domain":["geosite:cn","geosite:private"],"outboundTag":"Direct","type":"field"},{"ip":["geoip:cn","geoip:private"],"outboundTag":"Direct","type":"field"},{"network":"tcp,udp","outboundTag":"proxy","type":"field"}]}}

里面还是没有“Flow”这一部分，FYI。

**Comment by DearDawalish** [comment]
哦，我看了下官方文档，没有flow选项是可以的，那么这一项和v2rayN的就是一样的。WinXray设节点为服务器时，下方黑底白字的控制台的日志看看呢。  
你先在日志控制台右键选择“清屏”，然后激活节点，将这之后的日志都复制出来我看看

**Comment by Abracadabraba** [comment]
如下，请查阅。

已启动代理服务器，SOCKS端口:1081 HTTP端口:1082
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 windows/amd64)
A unified platform for anti-censorship.
2023/07/04 13:47:07 [Info] infra/conf/serial: Reading config: config.json
2023/07/04 13:47:07 [Warning] core: Xray 1.7.5 started
2023/07/04 13:47:07 tcp:127.0.0.1:56060 accepted tcp:www.google.com:80 [proxy -> proxy]
2023/07/04 13:47:08 tcp:127.0.0.1:56057 accepted tcp:149.154.167.41:80 [proxy -> proxy]
2023/07/04 13:47:08 tcp:127.0.0.1:56064 accepted tcp:149.154.167.41:80 [proxy -> proxy]
2023/07/04 13:47:08 tcp:127.0.0.1:56062 accepted tcp:149.154.167.41:443 [proxy -> proxy]
2023/07/04 13:47:08 tcp:127.0.0.1:56063 accepted tcp:[2001:67c:4e8:f002::a]:443 [proxy -> proxy]
已切换到服务器：	（我的地址）
2023/07/04 13:47:09 tcp:127.0.0.1:56066 accepted tcp:149.154.167.41:80 [proxy -> proxy]
2023/07/04 13:47:11 tcp:127.0.0.1:56068 accepted tcp:149.154.167.41:80 [proxy -> proxy]
2023/07/04 13:47:12 tcp:127.0.0.1:56071 accepted tcp:[2001:67c:4e8:f002::a]:443 [proxy -> proxy]
2023/07/04 13:47:12 tcp:127.0.0.1:56070 accepted tcp:149.154.167.41:443 [proxy -> proxy]
2023/07/04 13:47:12 tcp:127.0.0.1:56072 accepted tcp:149.154.167.41:80 [proxy -> proxy]
2023/07/04 13:47:13 tcp:127.0.0.1:56073 accepted tcp:149.154.175.100:443 [proxy -> proxy]
2023/07/04 13:47:13 tcp:127.0.0.1:56074 accepted tcp:[2001:b28:f23d:f003::a]:443 [proxy -> proxy]
2023/07/04 13:47:13 tcp:127.0.0.1:56075 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:13 tcp:127.0.0.1:56077 accepted tcp:www.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:13 tcp:127.0.0.1:56078 accepted tcp:edge-chat.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:14 tcp:127.0.0.1:56081 accepted tcp:[2001:b28:f23d:f003::a]:443 [proxy -> proxy]
2023/07/04 13:47:14 tcp:127.0.0.1:56080 accepted tcp:149.154.175.100:443 [proxy -> proxy]
2023/07/04 13:47:14 tcp:127.0.0.1:56082 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:14 tcp:127.0.0.1:56083 accepted tcp:www.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:14 tcp:127.0.0.1:56085 accepted tcp:gateway.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:15 tcp:127.0.0.1:56086 accepted tcp:edge-chat.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:15 tcp:127.0.0.1:56088 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:15 tcp:127.0.0.1:56089 accepted tcp:edge-chat.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:16 tcp:127.0.0.1:56090 accepted tcp:edge-chat.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:16 tcp:127.0.0.1:56092 accepted tcp:[2001:b28:f23d:f003::a]:443 [proxy -> proxy]
2023/07/04 13:47:16 tcp:127.0.0.1:56091 accepted tcp:149.154.175.100:443 [proxy -> proxy]
2023/07/04 13:47:16 tcp:127.0.0.1:56093 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:16 tcp:127.0.0.1:56094 accepted tcp:gateway.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:17 tcp:127.0.0.1:56097 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:17 tcp:127.0.0.1:56096 accepted tcp:edge-chat.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:17 tcp:127.0.0.1:56098 accepted tcp:edge-chat.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:19 tcp:127.0.0.1:56100 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:20 tcp:127.0.0.1:56102 accepted tcp:149.154.175.100:443 [proxy -> proxy]
2023/07/04 13:47:20 tcp:127.0.0.1:56103 accepted tcp:[2001:b28:f23d:f003::a]:443 [proxy -> proxy]
2023/07/04 13:47:20 tcp:127.0.0.1:56104 accepted tcp:149.154.175.100:80 [proxy -> proxy]
2023/07/04 13:47:21 tcp:127.0.0.1:56105 accepted tcp:149.154.167.92:443 [proxy -> proxy]
2023/07/04 13:47:21 tcp:127.0.0.1:56106 accepted tcp:[2001:67c:4e8:f004::a]:443 [proxy -> proxy]
2023/07/04 13:47:21 tcp:127.0.0.1:56107 accepted tcp:149.154.167.92:80 [proxy -> proxy]
2023/07/04 13:47:22 tcp:127.0.0.1:56110 accepted tcp:[2001:67c:4e8:f004::a]:443 [proxy -> proxy]
2023/07/04 13:47:22 tcp:127.0.0.1:56111 accepted tcp:149.154.167.92:80 [proxy -> proxy]
2023/07/04 13:47:22 tcp:127.0.0.1:56109 accepted tcp:149.154.167.92:443 [proxy -> proxy]
2023/07/04 13:47:23 tcp:127.0.0.1:56113 accepted tcp:www.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:23 tcp:127.0.0.1:56115 accepted tcp:149.154.167.92:80 [proxy -> proxy]
2023/07/04 13:47:24 tcp:127.0.0.1:56116 accepted tcp:149.154.167.92:443 [proxy -> proxy]
2023/07/04 13:47:24 tcp:127.0.0.1:56117 accepted tcp:[2001:67c:4e8:f004::a]:443 [proxy -> proxy]
2023/07/04 13:47:24 tcp:127.0.0.1:56118 accepted tcp:149.154.167.92:80 [proxy -> proxy]
2023/07/04 13:47:25 tcp:127.0.0.1:56120 accepted tcp:www.facebook.com:443 [proxy -> proxy]
2023/07/04 13:47:25 tcp:127.0.0.1:56119 accepted tcp:149.154.167.92:80 [proxy -> proxy]
然后会继续一行行的出现这些类似内容。

**Comment by Abracadabraba** [comment]
下面是V2rayN 里面的，FYI

配置成功
[VLESS] （我的地址）
启动服务(2023/7/4 14:03:02)...
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 windows/amd64)
2023/07/04 14:03:02 Using default config:  D:\Program Files\v2rayN\guiConfigs\config.json
A unified platform for anti-censorship.
2023/07/04 14:03:02 [Info] infra/conf/serial: Reading config: D:\Program Files\v2rayN\guiConfigs\config.json
2023/07/04 14:03:02 [Warning] core: Xray 1.7.5 started
2023/07/04 14:03:02 127.0.0.1:56934 accepted //mtalk.go**le.com:5228 [http -> proxy]
2023/07/04 14:03:02 tcp:127.0.0.1:56935 accepted tcp:91.108.56.171:443 [socks -> proxy]
2023/07/04 14:03:02 tcp:127.0.0.1:56936 accepted tcp:[2001:b28:f23f:f005::a]:443 [socks -> proxy]
2023/07/04 14:03:02 127.0.0.1:56938 accepted //gateway.fac**ook.com:443 [http -> proxy]
2023/07/04 14:03:02 tcp:127.0.0.1:56937 accepted tcp:91.108.56.171:80 [socks -> proxy]
2023/07/04 14:03:03 127.0.0.1:56939 accepted //gateway.fac**ook.com:443 [http -> proxy]
2023/07/04 14:03:03 tcp:127.0.0.1:56946 accepted tcp:91.108.56.171:443 [socks -> proxy]
2023/07/04 14:03:03 tcp:127.0.0.1:56947 accepted tcp:[2001:b28:f23f:f005::a]:443 [socks -> proxy]
2023/07/04 14:03:03 tcp:127.0.0.1:56948 accepted tcp:91.108.56.171:80 [socks -> proxy]
2023/7/4 14:03:03 系统代理设置改变
2023/07/04 14:03:03 127.0.0.1:56952 accepted //www.go**le.com:443 [http -> proxy]
2023/07/04 14:03:03 127.0.0.1:56954 accepted //edge-chat.fac**ook.com:443 [http -> proxy]
2023/07/04 14:03:03 127.0.0.1:56955 accepted //edge-chat.fac**ook.com:443 [http -> proxy]
2023/07/04 14:03:03 127.0.0.1:56958 accepted //edge-chat.fac**ook.com:443 [http -> proxy]
2023/07/04 14:03:03 127.0.0.1:56960 accepted //www.linkedin.com:443 [http -> proxy]
2023/7/4 14:03:03 当前服务的真连接延迟: 675 ms
2023/07/04 14:03:04 127.0.0.1:56962 accepted //alive.github.com:443 [http -> proxy]

**Comment by DearDawalish** [comment]
看起来也没什么奇怪的地方。会不会是你同时开了两个代理软件导致冲突了？现在vless节点都比较少，我找了个免费的vless，能顺利连上并访问谷歌，你试试看？

`vless://218fa143-d81a-e780-e6ce-6f43d211f28a@www.kernels.bid:443?path=%2Fws&security=tls&encryption=none&type=ws#[free-ss.site]`

![image](https://github.com/DearDawalish/WinXray/assets/135088527/3ccc70ba-5b71-4975-8f1d-c3eba8cd76b6)

如果这个你都连不上，得考虑下你电脑的环境问题了

**Comment by Abracadabraba** [comment]
![image](https://github.com/DearDawalish/WinXray/assets/108131195/77cee4a5-b2f8-4989-b41e-2c6c1c3c626b)
就很神奇！
我找的那个不能用，但是您这个可以。为什么呢？究竟是为什么呢？搞不懂。
我测试的时候都是测试一个关闭一个，所以不存在冲突。
我家里是windows11，我的节点还是同样的状况，所以看起来是节点不支持？节点还会挑软件？？？？
