### ISSUE TITLE
这个怎么破啊

### ISSUE THREAD

**Issue by lj2514321** [DearDawalish/WinXray#6]
app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > proxy/trojan: failed to flush payload > tls: failed to verify certificate: x509: certificate has expired or is not yet valid:

**Comment by DearDawalish** [comment]
这个是你代理服务器的证书过期了，和WinXray没有关系

**Comment by lj2514321** [comment]
找到解决方法了，把之前用过还留在电脑的加速器的网络适配器卸载了就好了。。。。
